---
  swagger: "2.0"
  info:
    title: "SFMOHD API"
    description: "Read Listing Data with Salesforce"
    version: "1.2.0"
  host: "salesforce.com"
  schemes:
    - "https"
  basePath: "/services/apexrest"
  produces:
    - "application/json"
  paths:
    /shortForm/list/{ContactID}:
      get:
        parameters:
          - in: path
            name: ContactID
            description: list of shortforms by contact
            required: true
            type: string
        description: "This returns the Listing information and its summary information."
        tags:
          - "Short form Application"
        responses:
          "404":
            description: Short form not found
          "200":
            description: successful operation
            schema:
              type: array
              items:
                $ref: '#/definitions/ShortForm'
          "400":
            description: Invalid ID supplied
    /shortForm/{shortFormId}:
      get:
        parameters:
          - in: path
            name: shortFormId
            description: ID of shortform
            required: true
            type: string
        description: "This returns the Listing information and its summary information."
        tags:
          - "Short form Application"
        responses:
          "404":
            description: Short form not found
          "200":
            description: successful operation
            schema:
              $ref: "#/definitions/ShortForm"
          "400":
            description: Invalid ID supplied
    /shortForm/:
      post:
        parameters:
        - in: body
          name: body
          description: short form placed
          required: false
          schema:
            $ref: "#/definitions/ShortForm"
        tags:
        - "Short form Application"
        responses:
          "404":
            description: Short form not found
          "200":
            description: Success
            schema:
              $ref: "#/definitions/ShortForm"
          "400":
            description: Invalid ID supplied
    /shortForm/delete/:
      post:
        description: deletes specified application
        parameters:
        - name: id
          in: query
          description: ID shortForm To Delete
          type: string
          required: true
        responses:
          200:
            description: OK
    /shortForm/contact/delete:
      post:
        description: deletes specified contact from household
        parameters:
        - name: id
          in: query
          description: ID of contact to delete
          type: string
          required: true
        responses:
          200:
            description: OK

  definitions:
    ShortForm:
      type: "object"
      description: "ShortForm for housing"
      properties:
        ID:
          type: "string"
          description: "Sfdc ID"
        Primary Applicant:
          $ref: '#/definitions/Contact'

        Secondary Contact:
          $ref: '#/definitions/Contact'

        Household Members:
          type: array
          items:
              $ref: '#/definitions/Contact'
        Works in San Francisco:
          type: "boolean"
          description: "currently works In SF"
        Current Status:
          type: "string"
          description: "homeless, renting, home owner?"
        Years Homeless:
          type: "integer"
          description: "number of years homeless"
        isResident:
          type: "boolean"
          description: "is a resident of SF"


    Contact:
      type: "object"
      description: "Applicant Contact"
      properties:
        ID:
          type: "string"
          description: "sfdc ID"
        firstName:
          type: "string"
          description: "first name"
        lastName:
          type: "string"
          description: "the listing id"
        DOB:
          type: "string"
          description: "date of Birth"
        email:
          type: "string"
          description: "email"
        phone:
          type: "string"
          description: "phone number"
        address:
          type: "string"
          description: "Address"
        city:
          type: "string"
          description: "City"
        state:
          type: "string"
          description: "State"
        zip:
          type: "string"
          description: "Zip"
        mailingAddress:
          type: "string"
          description: "Mailing address"
        mailingCity:
          type: "string"
          description: "Mailing City"
        mailingState:
          type: "string"
          description: "Mailing State"
        mailingZip:
          type: "string"
          description: "Mailing zip"
        gender:
          type: "string"
          description: "gender"
        lgbt:
          type: "boolean"
          description: "lgbt"
        hiv:
          type: "boolean"
          description: "hiv"
        holdsCOP:
          type: "boolean"
          description: "has a certificate of preference"
        holdsDTP:
          type: "boolean"
          description: "has displaced tenant preference"
        relationship:
          type: "string"
          description: "relationship to primary applicant"
        annualIncome:
          type: "number"
          description: "displaced tenant pref"
        incomeType:
          type: "string"
          description: "displaced tenant pref"

